// Checks if its the first time loading the site
var firstTime = localStorage.getItem("loadedBefore");

// Stores cookie of loadedBefore if its the first time
if (!firstTime) {
    localStorage.setItem("loadedBefore", 1)
    localStorage.setItem("lang", 1);
}

// Stores a dictionary of all text to be displayed
const dict = {
    timelineTitle: {
        en: `The Timeline of RL Ireland`,
        ga: `Amlíne de RL Ireland`
    },
    pageContent: {
        en: `<h2>Origins</h2>
        <p>RLI was created in somewhat controversial circumstances, naturally. This is the story <strong>as far as we know</strong>.<br><br>
        Two lads from Donegal called Joseph and Darcy (you may have heard of them) were in 3rd year of secondary school and didn’t know many people around them who played Rocket League. 
        So Darcy had the idea to create RL Ireland, a place where all Irish Rocket League players can come together and play together, 
        a place where they could find teammates and hold tournaments. He told Joseph about this, and when Joseph got home, he made the Facebook page.<br><br>
        And that is how RLI began.</p>
        <h2>2015</h2>
        <p>The RL Ireland Facebook page was created on the 28th of December, and new members started trickling in.</p>
        <h2>2016</h2>
        <p>2016 was a fairly quiet year overall, and it's difficult to find out things about this time, but here's a bit of what we know:<br><br>
        Enwrong (along with one of his friends, sasm8) made an RL Ireland website, completely unrelated to the Facebook page, specifically for one tournament
        aimed at Irish Rocket League players. It didn't have much success, but through the process of making it, Enwrong found the Facebook page and joined it.<br><br>
        Enwrong, Darcy and XtremeNolaner all organised tournaments in a fairly random manner, which kept a steady stream of new people joining and kept the page active.
        Enwrong attempted a league system which unfortunately didn't catch on after the first season, however he did win the top division with Daithí, which is only the second
        RLI tournament he has ever won (lmao washed). Many a spontaneous 1v1 tournament was also organised.
        Around July 2016, XtremeNolaner made the Discord server for RLI.
        </p>
        <h2>2017</h2>
        <p>The first RLI LAN took place in The Convention Center in Dublin, called GamerCon, on the 18th and 19th of March. Dave Forehead, Daithi and Tully won, with Luke, Dormer and 1Junior1 (LivingLazerHD at the time)
        coming second. Lynxi, Airside, LTXSam and Warfare also played, Enwrong adminned the event, and Pandaa didn't play but showed up anyway.<br><br>
        After an argument between Darcy and Enwrong, Enwrong left the server in June. XtremeNolaner also left around this time after he sold his computer. This left Darcy
        on his own to run tournaments, and since he couldn't run tournaments as often as before by himself, RLI became a lot quieter than before. This is considered by some to be the beginning of the "dark ages" of RLI,
        however in reality tournaments were still being organised and the Discord server received an overhaul, with new text channels and roles being introduced.<br><br>
        Walshy should also get a small mention here for willingly donating in-game items for the prize pools of the occasional tournament that was organised.<br><br>
        The Games eXpo Ireland LAN took place in the RDS in Dublin on the 26th of November, with Daithi and XDarkArcticX winning, LTXSam and Warfare coming second and Dave Forehead and
        Enwrong commentating. Dave Forehead later posted to Facebook about the GXI LAN that kickstarted the revival of RLI.
        <br><br><img src="../assets/Dave-Forehead-FB-post.png" alt="A picture of Dave Forehead's post on Facebook."><br><br>
        On the 28th of November, Dave Forehead was promoted to admin of the Facebook page by Darcy and XtremeNolaner gave him ownership of the discord server. Enwrong was also made admin on both platforms.
        The first staff meeting happened a day later between the four admins and the newest staff members, who were offered a place based on how long they'd been in the community and how active they'd been.
        They were Tully, Walshy and Daithi. The RLI twitter account was made on the 30th of November.<br><br>
        The first tournament RLI ever streamed was a 2v2 christmas event on the 3rd of December, won by Dry and Fusure. Back then we had tiered tournaments.
        <br><br><img src="../assets/RLI-christmas-2v2-tournament-results.jpg" alt="A spreadsheet of the tournament results."><br><br>
        The Dry vs McCluvin 1v1 showmatch helped bring RLI to the attention of people outside of Ireland for probably the first time, with help from DigitalBacon.
        Dry was constantly in the top 10 on the 1s leaderboard in the world at the time, and appeared on JohnnyBoi's stream.</p>
        <h2>2018</h2>
        <p>
        RLI became very active in 2018 as tournament after tournament was organised, nearly all of which were streamed, leading to faster growth for the community.
        RLI held a 6mans invitational tournament on the 19th of January, featuring the likes of Redeyes, Lawlurr, Mugg, Barzey, Mayday and Fusure (with blah coming in as a sub in the last match).
        This was also the first time an RLI event was won by a console player.<br><br>
        Barzey and Mayday became Operators on the 20th of January, but Mayday left shortly afterwards.<br><br>
        Team RLI (captained by Redeyes) took on Nixus' competitive team on the 24th of January, however the RLI team had barely played together and unfortunately lost.<br><br>
        RLI opened staff applications on the 13th of February, after which Pandaa, CaptainQwark and ItsJustAbe became Moderators. bNy became a graphic designer for RLI and 1Junior1 became a streamer.<br><br>
        RLI uploaded to their YouTube channel for the first time on the 25th of February with highlights of it's first ever 12 Titans tournament. They continued to post highlight videos and a couple of podcasts for a brief
        amount of time afterwards.<br><br>
        The RLI-Helper bot was introduced to the Discord server on the 10th of March, as Dave Forehead had gotten fed up with having to give people new roles in the server on a constant basis.<br><br>
        bNy made the RLI logo on the 26th of May, and the community was formally renamed from Rocket League Ireland to RL Ireland.<br><br>
        On the 24th of June, the <a href="https://liquipedia.net/rocketleague/RL_Ireland/Q-CON/2018">Q-Con 2v2 LAN</a> took place in Belfast, which was considered a massive success. Mugg and Fusure won with Dry and Crungus came second. Dave Forehead and Tully did most of the commentating on
        the day with the occasional interview and guest caster throughout the day. Darcy adminned the event, with help from Dannyboy. RLI merchandise was available for the first time at this point, with black and white hoodies
        and t-shirts on offer.
        <br><br><img src="../assets/RLI-belfast-lan-picture.jpg" alt="A picture of everyone from the Q-Con LAN together."><br><br>
        Redeyes won the Seasonal Elite Championship on the 13th of July. The concept of the tournament (attributed to Enwrong) was that a player's performance in the tournament was converted to points, and the top 6 played a 6mans tournament to
        decide a winner.<br><br>
        The Dublin Games Festival (DGF) LAN took place on the 24th of November, with The Dubliners, consisting of ItsPureLogic, Mugg and Fusure, winning and Aviators, made up of Enwrong, Pandaa and Durkan, coming second in a final that finished a minute before the internet would be turned off.
        Dave Forehead adminned the event, and ran a last minute stream off of his computer.<br><br>
        <img src="../assets/picture-of-dgf-lan.jpg" alt="A picture of the DGF LAN with people at the computers playing."><br><br>
        On the 7th of December, Redeyes became our Seasonal Elite Champion for the second time in a row.</p>
        <h2>2019</h2>
        <p>
        Enwrong started the 6mans league again on the 8th of January, which turned out to be much more successful than his previous attempt back in 2016, with over 30 participants and 4 divisions. Demoqz won it the first month.<br><br>
        RLI-Times was introduced on the 7th of February, a text channel within the Discord server run by Ghost and Blah that posted about what was going on in the RLI server from time to time.<br><br>
        RLI announced on the 8th of March that it planned to host it’s own LAN event for the first time ever in a gaming bar down in Cork.<br><br>
        On the 13th of March, Tully got demoted from Operator while Pandaa was promoted to Operator. On the 16th, carrickdan and John_Aka_Alwayz got promoted to Moderator, and RLI opened its Moderator applications for the second time. Captain Qwark left the staff team on the 6th of April to focus on exams<br><br>
        On the 7th of April, RLI was officially announced as European Games Week's Rocket League partner for their LAN event in June.<br><br>
        Daithí and Barzey left the staff team to focus on exams on the 8th of April.<br><br>
        RLI held it's first ever self-run LAN event on the 20th of April. Suitably called the RLI LAN, it took place in the 365itHub in Cork. It was a 3v3 LAN with 12 teams entering. 
        Joseph (with help from Walshy) ran the event. Lynxi took a lot of photos for himself and for RLI. Dave Forehead and NuaLaoch casted the event with people coming in for casual interviews now and again. Most importantly, the event was won by FML, consisting of Fusure, Mugg and ItsPureLogic, with Yurt (Walshy, Adzer and Demoqz) coming second and Nuclear Storm Gaming (Enwrong, Arctic and Pandaa) coming third. Adzer was named MVP of the tournament and Pat. was given the Redeyes Redemption award, for playing the most above expectations, funded by JToPrey (who won a giveaway on Redeyes' stream, hence the name).<br><br>
        Carrickdan and John_aka_Alwayz got promoted to Operator on the day as well. Shortly after, LovelyCans, Demoqz and LTXSam were made Moderators.<br><br>
        <img src="../assets/rli-lan.jpeg" alt="A picture of the RLI LAN"><br><br>
        Mugg was announced as the 6mans Season 2 winner on the 25th of April. Walshy left the staff team on the same day after being with them for over a year.<br><br>
        On the 3rd of May, the Discord server reached the 500 member mark.<br><br>
        Redeyes became the third 6mans winner on the 5th of June.<br><br>
        Enwrong started a new 2v2 league that ran alongside the 6mans league on the 10th of June. The 4th season of 6mans started on the 13th, with Dave Forehead and John_aka_Alwayz in charge of it this time, instead of the usual Enwrong. A group of 6mans moderators helped them run it as before.<br><br>On the 14th of June, Dave Forehead updated the RLI Helper Bot so that it wouldn’t drop offline randomly.<br><br>On the 18th of June, Dave Forehead announced that RLI would enter ERLS (later renamed to IEL – Imperial Esports League).<br><br>On the 19th of June, Carrickdan decided to leave the RLI staff team.<br><br>On the 30th of June, RLI announced that it’d be helping run the RL tournament at Q-con XXVI.<br><br>On the 9th of July, Walshy and Redeyes were announced as the first of RLIs 2v2 league winners.<br><br>
        Signups for Season 2 of the 2v2 league were announced on the 13th of July, along with the major news that NSG would sponsor the top tier of the league, meaning the winners of Season 2 would be taking €50 as a prize.<br><br>JKee became the sole member of RLI’s media team on the 17th of July.<br><br>Jxffa became the 6mans Season 4 champion on the 27th of July.<br><br>RLI announced on the 29th of July that they would be helping Insomnia run a LAN.<br><br>
        On the 2nd of August, Enwrong and John_aka_Alwayz realised that Dave Forehead was onto something with the whole “preserving history" thing and made Liquipedia pages for <a href="https://liquipedia.net/rocketleague/RL_Ireland/Q-CON/2018">Q-Con 2018</a>, <a href="https://liquipedia.net/rocketleague/RL_Ireland/DGF">DGF 2018</a> and <a href="https://liquipedia.net/rocketleague/RL_Ireland/LAN_Cork/2019">RLI LAN 2019</a>.<br><br>
        On the 5th of August, Dave Forehead added the RLI logo as an emote to the Discord server.<br><br>On the 7th of August, LovelyCans was promoted to Operator and Jxffa was promoted to Moderator.<br><br>On the 21st of August, Insomnia Dubin confirmed they were having a Rocket League tournament at their event.<br><br>On the 1st of September, <a href="https://liquipedia.net/rocketleague/RL_Ireland/Q-CON/2019">Q-Con 2019</a> took place. Mugg & Fusure won the competition, with Redeyes and late sub Enwrong coming second. Enwrong adminned the event with help from Dave Forehead and a host of other members of the RLI staff team.<br><br><img src="../assets/q-con-2019.jpg" alt="A picture of Q-Con 2019"><br><br>A server rules channel was officially introduced into the Discord server on the 7th of September.<br><br>
        Demoqz left the staff team on the 9th of September.<br><br>EGW was cancelled on the 13th of September. It was a massive moment for esports in Ireland and Europe that year, sending shockwaves not just through RLI but through esports across the country. No-one was quite sure what would happen.<br><br>However, class acts, full time legends and absolute heroes Enwrong and Dave Forehead ensured that the Rocket league event from EGW wasn’t cancelled and instead took place in a gaming cafe that was owned by the EGW event organisers, meaning that those who paid for accommodation, travel and tickets still had something to look forward to.<br><br>The 5th season of RLI 6mans came to an end on the 19th of September with Mugg becoming the first and only two-time Premier champion. <br><br>Later that day, Barzey returned to the staff team as Moderator, along with Luachra.
        <br><br>The re-named <a href="https://liquipedia.net/rocketleague/RL_Ireland/Giga-Bite_Cafe_LAN">Giga-byte LAN</a> took place on the 21st of September. Adzer, Ryan and Virtuoso all won their first ever LAN event, defeating LAN regulars Mugg, Fusure and Blah in the final. The fully foreign team of sadGreen, Messy.DD and Thieu.DD came third.<br><br>John_aka_Alwayz and Dave Forehead adminned the event, with Enwrong and Nualaoch casting the day’s action.<br><br><img src="../assets/giga-byte-lan.jpg" alt="A picture of players playing at the Giga-Byte LAN"><br><br>RLI’s 1s league was announced on the 23rd of September, meant to replace the old 6mans.<br><br>Community games night was introduced on the 4th of October. Run by new Moderators Barzey and Luachra, a games night happened roughly every fortnight and it was designed to encourage newer people in the server to get to know everyone better.<br><br>
        Carrickdan started RLI Weekly on the 14th of October, a parody weekly newsletter that commented on the weekly goings-on in the server, primarily focusing on the beef and drama caused by the members.<br><br>RLI’s seasonal 2v2 tournament took place on the 20th of October. Ghost and Jakey beat Shallow and Weetabix in the Tier 1 final, while the Tier 2 final was won by Ryan and Roadman John over AdequateLlama and Poggs.<br><br>On the 27th of October, RLI’s master IEL team, consisting of Jxffa, Walshy, Fusure, and LovelyCans as sub, won in the Grand Finals. Later, the challenger team, consisting of Luachra, Littledude37, Kipp and Ruffs as sub, made it to the Grand finals but sadly couldn’t repeat the same result as the master team.<br><br>
        RLI’s new major league was announced on the 1st of November, called RLI Superstars, or RLIS. The main idea of RLIS was to incorporate 1s, 2s and 3s all into the one league.<br><br><a href="https://liquipedia.net/rocketleague/Insomnia_Dublin">Insomnia Dublin</a> took place on the 9th of November, becoming a record-breaking 4th LAN in the same year for RLI. Mugg, Fusure and Virtuoso took 1st place, with Virtuoso taking MVP as well. Demoqz, JKee and Classy took an arguably surprising 2nd place also. Enwrong adminned the event, and he was assisted by John_aka_Alwayz and LTXSam. Dave Forehead casted the day’s action, joined by Enwrong for the final.<br><br>Darcyyyy stepped down from Admin to Moderator on the 16th of November.<br><br>As part of RLI’s end-of-year announcement on the 31st of December, Luachra was promoted to Operator.</p>
        <h2>2020</h2>
        <p>RLI’s second ever independent LAN, set to take place in Ballymena, was announced on the 3rd of January.<br><br>RLI’s winter 3v3 tournament took place on the 25th of January, with a record breaking 0 DQ’s throughout the day. Redeyes, Walshy and Shallow took the win over Demoqz, Arctic and Pandaa. In Tier 2 Ryan, BigBallsBrowne and Ruffs beat AdequateLlama, Spf and Pokewithastick in the final.<br><br>The first season of <a href="https://liquipedia.net/rocketleague/RL_Ireland/RLIS/Season_1">RLIS</a> finished on the 26th of January.<br><br>Squid-G and Ryan were made Moderators on the 16th of February.<br><br>RLI’s <a href="https://liquipedia.net/rocketleague/RL_Ireland/RL_Ireland%27s_Ballymena_LAN_2020">Ballymena LAN</a> took place on the 29th of February. NSG (Arctic, Pandaa and Demoqz - shouted at by Enwrong in the final) won 4 - 2, beating Mugg, Fusure and JKee in the final with Arctic taking the MVP award.<br><br>
        Dave Forehead casted the majority of the tournament with Nailer, John_aka_Alwayz ran the event and new staff member Squid-G took pictures<br><br><img src="../assets/ballymena-lan.jpg" alt="A picture of everyone at the Ballymena LAN><br><br>RLI’s Dropshot Special took place on the 15th of March. S E V E N, Adzer and Hiccup won it, with Fassbendered, Lapsley and JaRyan coming second.<br><br>RLI’s first ever table quiz happened on the 22nd of March.<br><br>RLI’s <a href="https://liquipedia.net/rocketleague/RL_Ireland/Irish_12_Titans/Season_4"><br><br>4th Twelve Titans</a> event came to an end on the 29th of March with Ineffable beating Robkiernxn in a spectacularly high-quality final.<br><br><a href="https://liquipedia.net/rocketleague/RL_Ireland/RLIS/Season_2">RLIS Season 2</a> came to an end on the 3rd of April.<br><br>
        LovelyCans said “xD" 1000 times in the server by the 10th of April. There was an announcement made about this for some bizarre reason, and he felt the need to tag everyone about it, which I suppose would be a very Cans thing to do. Obviously, such a monumental achievement must be recorded here.<br><br>Squid-G announces the addition of the custom games section to the RLI server on the 12th of April, a place for setting up modded games in RL.<br><br>The first <a href="https://liquipedia.net/rocketleague/RLIreland/Irish_Elite_Cup/1">Irish Elite Cup</a> (IEC) took place on the 2nd of May, with Robkiernxn, Mugg and Shallow winning it.<br><br>The <a href="https://liquipedia.net/rocketleague/RL_Ireland/Spring_2020/2v2">RLI Spring 2v2</a> tournament took place on the 3rd of May, with Story Bud (Mugg & Robkiernxn) winning tier 1 and The Ladaroos (Fassbendered & Fine) winning the 2nd tier.<br><br>
        RLI opened up staff applications on the 4th of May to everyone in the server in order to expand the staff team to match the growth of the server.<br><br>RLI took on 7 new staff members on the 9th of May. Mul, Gillzo, Aidan, Lynsk, JaRyan and Wazzito all became moderators. Res, due to his hard work on the RLIS spreadsheet immediately became an operator, and Ryan was also promoted to operator. RLI founder, Darcy, decided to leave the staff team.<br><br>Later that day, the second <a href=https://liquipedia.net/rocketleague/RL_Ireland/Irish_Elite_Cup/2>IEC</a> took place with Mugg, Robkiernxn and APS taking the win.<br><br>The third <a href="https://liquipedia.net/rocketleague/RL_Ireland/Irish_Elite_Cup/3">IEC</a> took place on the 16th of May with 3 new winners in Arctic, Pandaa and Pengu. <br><br>Dave Forehead brought out an update to the RLI Helper on the 18th of May that introduced the >me and >vintage_dyk commands and also updated the >dyk command to show slightly more updated facts.<br><br>
        The fourth <a href="https://liquipedia.net/rocketleague/RL_Ireland/Irish_Elite_Cup/4">IEC</a> took place on the 23rd of May with Pandaa, Adzer and Ryan winning. <br><br><a href="https://liquipedia.net/rocketleague/RL_Ireland/RLIS/Season_3">RLIS Season 3</a> came to an end on the 31st of May with the winners being: <br><br>RLI entered IEL Season 6 on the 9th of June<br><br>The RLI discord server hit 800 members on the 18th of June and to celebrate Barzey kickstarted the community games night once again.<br><br>Maydayyy, Mugg and Robkiernxn won the sixth <a href="https://liquipedia.net/rocketleague/RL_Ireland/Irish_Elite_Cup/6">IEC</a> tournament on the 20th of June.<br><br>RLI announced its <a href="https://www.patreon.com/rlireland">patreon</a> page on the 24th of June. There were 3 tiers: Johnstown, Tipp and North Dublin.<br><br>
        The RLI 6mans bot was remade on the 28th of June.<br><br>The 7th <a href="https://liquipedia.net/rocketleague/RL_Ireland/Irish_Elite_Cup/7">IEC</a> took place on the 4th of July, won by Shallow, Spectre and Robkiernxn.<br><br>The RLI 6mans bot was updated on the 1st of August to have different tiers of 6mans queues.<br><br>
        <a href="https://liquipedia.net/rocketleague/RL_Ireland/RLIS/Season_4">RLIS Season 4</a> finished on the 3rd of August.<br><br>The RLI 1v1 Summer seasonal cup took place on the 9th of August. Robkiernxn took 1st place in the top tier and LovelyCans won in tier 2.<br><br>RLI won the IEL master title for a second time with LTXSam, EliteSpartan (now known as Shane) and Jxffa on the 16th of August. Winning made RLI the joint most successful team in IEL at that point.<br><br><a href="https://liquipedia.net/rocketleague/RL_Ireland/Irish_Elite_Cup/7">IEC #7</a> was played after a brief absence on the 22nd of August, and Shallow, Spectre and Robkiernxn won.<br><br>A new IEC format was announced 24th of August. The new format made players play in a playoffs stage before the main event, whereas before IEC was just a one-day event.<br><br>At the same time, Jxffa and Gillzo left the staff team.<br><br>
        RLI announced on the 26th of August it’s one of a kind merch, RLI face masks.<br><br>John_aka_Alwayz announced on the 28th of August that he had put the top tier of RLIS seasons 1-4 on Liquipedia.<br><br>The final phase of <a href="https://liquipedia.net/rocketleague/RL_Ireland/Irish_Elite_Cup/8">IEC #8</a> took place on the 7th of September with Yem, Demoqz and Maydayyy winning. <br><br>RLIS Season 5 was announced on the 8th of September, and at the same time GraHa was made a moderator.<br><br>The final stage of <a href="https://liquipedia.net/rocketleague/RL_Ireland/Irish_Elite_Cup/9">IEC #9</a> took place on the 21st of September with Wazzito, Colin and Littledude as the winners. <br><br>RLI ran the Autumn Solo-standard Seasonal Cup on the 24th of October. The winners were Aidan, JToPrey and Domhnaill.<br><br>
        <a href="https://liquipedia.net/rocketleague/RL_Ireland/RLIS/Season_5">RLIS season 5</a> came to a close on the 19th of November with no sign of another RLIS. <br><br>After 2 qualifiers and playoffs with 4 gatekeepers, Ineffable became champion of <a href="https://liquipedia.net/rocketleague/RL_Ireland/Irish_12_Titans/Season_5">RLI 12 Titans Season 5</a> on the 22nd of November.<br><br>Luachra decided to leave the staff team from his operator position on the 26th of November. He apparently did nothing anyway.<br><br>RLI announced on the 2nd of December that it was going to enter Templar League’s 2s league, a league very similar to IEL. The teams were to be managed by LovelyCans, with Dave Forehead as an assistant.<br><br>An international showmatch between Esports Wales and Ireland Esports took place over 3 different esport games on the 5th of December. Pandaa, Shallow and Spectre represented Ireland Esports in Rocket League and won 3-1.<br><br>
        RLI hosted its 2v2 Holiday Hoops tournament on the 6th of December, with Ryan and Adzer making themselves kings of the dunk house.<br><br>Enwrong announced on the 8th of December that signups were open for the RLI Super Omega Ultimate Cup, a name which Dave Forehead took huge issue with for some reason. The Super Omega Ultimate Cup was one of the largest online tournaments RLI had ever hosted in terms of prize pool size and it was intended to boost people’s interest in the game over the holidays considering the unfortunate lack of LAN events in 2020.<br><br>Aidan left the staff team on the 16th of December, followed by LTXSam on the 19th.<br><br>
        <a href="https://liquipedia.net/rocketleague/RL_Ireland/Super_Omega_Ultimate_Cup">RLI’s Super Omega Ultimate Cup</a> (SOUC) started on the 27th of December, with the 3s event. SOUC was a 2-day event where individuals won points based on where they finished in a 3s tournament and a 2s tournament, with the top 6 getting a cash prize. The 3s tournament was won by Yurt (Redeyes, Demoqz, Future), and in 2nd place came Doggery (Arctic, Pandaa, Ineffable). The 2s event took place the day after and was won by Well Bai (Shallow and Ineffable), who beat finalists Yemoqz (Yem, Demoqz).</p>
        <h2>2021</h2>
        <p>Dave Forehead made his traditional end of year announcement on the 1st of January by announcing that RLI were opening staff applications.<br><br>JengaBenga, Pokewithastick, Royzer, Coombs and Wrench all joined the staff team on the 15th of January.<br><br>The <a href="https://www.tiktok.com/@rl_ireland">RL Ireland TikTok</a> account was made on the 18th of January, and the top 5 clips of the week were posted there on a (semi) regular basis. <br><br>
        The <a href="https://liquipedia.net/rocketleague/RL_Ireland/WYLDE_Rocket_Series">Wylde Rocket Series</a> (WRS) was announced on the 2nd of February. WRS was a series of monthly tournaments where teams earned points based on their finishes and the teams with the highest points qualified for the major event in June. The whole set of events was sponsored by the Irish based esports organisation Wylde. On an unrelated note (but on the same day) the RLI 6mans bot got its captains update. Players could now choose if they wanted the teams to be decided randomly by the bot or by captains.<br><br>
        The <a href="https://liquipedia.net/rocketleague/RL_Ireland/WYLDE_Rocket_Series/February">first WRS monthly</a> event took place on the 13th of February. Team (Shallow, Spectre and Aenia) took the win over Carbon Zero (Shane, Lynsk, Futura).< br><br>RLI Madra, one of RLI’s five Templar League teams won the Knights Division on the 20th of February. GraHa and Bonkersbott made it happen in the playoffs, Anthony played a crucial role during the season, and Dave Forehead was there to provide the water and orange slices.<br><br>It was 2/4 for RLI in Templar League as RLI Sneachta, LTXSam and Dlynch, delivered the goods to win the Kings division, with Fassbendered playing his part through-out the season as well.<br><br>The 2v2 Spring Cup took place on the 27th of February, an unusual cup for RLI as it was only open to players C3 or lower. UwU Stepdad (Wrench and Aaron) won the event against Oaties (CaptainQwark and Dimitrov) in the final.<br><br>
        <a href="https://liquipedia.net/rocketleague/RL_Ireland/WYLDE_Rocket_Series/March">WRS Monthly #2</a> took place on the 14th of March with DogWithALog (Yem, Colin, HammerSt – as it would turn out, Wazzito was secretly playing on HammerSt’s account) taking it in the final against Me and the Boys (Robkiernxn, Shallow and Halden).<br><br>The first ever Challenge the Staff event took place on the 20th of March. There were 3 tiers of staff teams for members of the community to challenge. The staff teams earned a 100%-win record over the community.<br><br>The RLI discord server hit 1000 members on the 1st of April. No, this is not a joke.<br><br><a href="https://liquipedia.net/rocketleague/RL_Ireland/Irish_12_Titans/Season_6">12 Titans S6</a> took place on the 4th of April with Shallow surprising many to take the top spot over Colin in the final. Ineffable said on the day, “What did you have for breakfast?" and Shallow famously replied “Easter egg".<br><br>
        IEL Season 8 came to a close on the 18th of April with the Master, Challenger and Prospect teams all making playoffs. The Prospect team had the best run, getting to the semi-finals. Coombs also left the staff team on this day.<br><br>
        <a href="https://liquipedia.net/rocketleague/RL_Ireland/WYLDE_Rocket_Series/April">WRS Monthly #3</a> took place on the 25th of April with Me and the Boys (Robkiernxn, Spectre and Shallow) getting revenge over DogWithALog (Yem, Colin and HammerSt/Wazzito).<br><br>JaRyan left the staff team on the 1st of May, followed by Ryan on the 6th, and then Wrench on the 18th.<br><br><a href="https://liquipedia.net/rocketleague/RL_Ireland/WYLDE_Rocket_Series/May">WRS Monthly #4</a> took place on the 23rd of May with new winner Carbon Zero (Shane, Futura and NKS) beating Hoovers (Smokez, Trace (formerly Cian) and Staar) in the final.<br><br>The Seasonal Solo Standard cup took place on the 30th of May with LTXSam, Finbarr and barmanitan winning in the final against Mul, Gillzo and P1ayer 0n3.<br><br>
        The original <a href="https://docs.google.com/document/d/1oW8iqr8yDmqB2GQdnPGQaZ48TGfP0UFd122TOVHryPg/edit?usp=sharing">history book</a> was updated on the 3rd of June, as Dave Forehead had grown lazy, leaving Lynsk to pick up the slack.<br><br>Wylde and RLI partnered up for a giveaway on the 11th of June. The winners would receive some lovely Wylde merch when the draw happened after WRS Monthly #5.<br><br><a href="https://liquipedia.net/rocketleague/RL_Ireland/WYLDE_Rocket_Series/June">WRS Monthly #5</a> took place on the 13th of June, with Me and the Boys (Shallow, Robkiernxn and Spectre) taking the win over DogWithALog (Colin, Yem and HammersSt/Wazzito). Afterwards, the draw for the giveaway happened, with AdequateLlama, Murph and most importantly YummyUranium winning.<br><br>On 15th of June, Squid-G left the staff team. As the staff had lately been dropping like flies, Dave Forehead opened staff applications the day after.<br><br>
        On the 19th of June, a competitive ruling was announced after it had been discovered that Colin, Yem and HammerSt, who made up the team of DogWithALog, had been intending to cheat in the upcoming WRS Major. They intended to have another player, called Wazzito, who had previously been banned from RLI, play on HammerSt’s account. As well as this, they approached a high-level external bubble player to play on Colin’s account. There was a veritable shitshow in #general in the hours following, with a few more people getting bans and mutes. #general was locked for the night, and #memes-nsfw was hidden.<br><br>
        The staff application form deadline was moved twice, first to the 26th of June, and the to the 22nd, as the Major was coming up and Moderators were desperately needed to handle the event well. On June 22nd, the 5 new Moderators were announced: YummyUranium, Bonkersbott, Dlynch, Panicjungle and Jacko.
        </p>
        `,
        ga: `<h2>Bunús</h2>
        <p>Bhí RLI crúthaithe i gcúinsí conspóideach, dar ndóigh. Is é seo an scéal <strong>go bhfios dúinn</strong>.<br>
        Bhí dhá leaid ó Tír Chonaill darbh ainm Joseph agus Darcy (tá seans ann gur chuala tú faofa) sa tríú bhliain ar scoil. Ní raibh a fhios acu ar mórann daoine thart orthu a d'imir Rocket League.
        Mar sin, bhí an smaoineamh ag Darcy "Rocket League Ireland" a chrúthú, áit a dtiocfadh le imreoirí Éireannach a theacht le chéile agus imirt le chéile,
        áit a dtiocfadh leo cairde a dhéanamh agus comórtais a chrúthú. D'inis Darcy seo do Joseph, agus chomh luath agus a bhí Joseph sa bhaile, chruthaigh sé an leatheanach Facebook.<br>
        Agus is é sin an dóigh gur thoisigh Rocket League Ireland.</p>`
    },
    langChangeText: {
        en: `Tá an leatheanach seo ar fáil i <button type="button" onclick="langChange()" class="text-button"><strong>nGaeilge</strong></button>.`,
        ga: `This page is available in <button type="button" onclick="langChange()" class="text-button"><strong>English</strong></button>.`
    },
    headerBanner: {
        en: `
        <li><a href="../index.html"><img src="../RLI_logo_1.png" alt="RL Ireland logo" class="logo"></a></li>
        <li><a href="../index.html">Home</a></li>
        <li><a href="timeline.html" id="current-page">Timeline</a></li>
        <li><a href="../Quotes/quotes.html">Quotes</a></li>
        <li><a href="../Tournaments/tournaments.html">Tournaments</a></li>
        <li><a href="../Personalities/personalities.html">Personalities</a></li>`,
        ga: `
        <li><a href="../index.html"><img src="../RLI_logo_1.png" alt="RL Ireland logo" class="logo"></a></li>
        <li><a href="../index.html">Baile</a></li>
        <li><a href="timeline.html" id="current-page">Amlíne</a></li>
        <li><a href="../Quotes/quotes.html">Frásaí</a></li>
        <li><a href="../Tournaments/tournaments.html">Turnaimint</a></li>
        <li><a href="../Personalities/personalities.html">Pearsantachtaí</a></li>`
    }
}

// Changes language and stores cookie once changed
function langChange() {
    if (localStorage.getItem("lang") == 1) {
        localStorage.setItem("lang", 2);
        return location.reload();
    } else if (localStorage.getItem("lang") == 2) {
        localStorage.setItem("lang", 1);
        location.reload();
    }
}

// Loads page with language choices for title
if (localStorage.getItem("lang") == 1) {
    document.getElementById("title").innerHTML = dict.timelineTitle.en;
    document.getElementById("innerPageContent").innerHTML = dict.pageContent.en;
    document.getElementById("langChangeText").innerHTML = dict.langChangeText.en;
    document.getElementById("headerBanner").innerHTML = dict.headerBanner.en;
} else if (localStorage.getItem("lang") == 2) {
    document.getElementById("title").innerHTML = dict.timelineTitle.ga;
    document.getElementById("innerPageContent").innerHTML = dict.pageContent.ga;
    document.getElementById("langChangeText").innerHTML = dict.langChangeText.ga;
    document.getElementById("headerBanner").innerHTML = dict.headerBanner.ga;
} else {
    console.log("Error: language not loaded correctly");
}